# Site settings
title: Yichieh Chen (@chairco)
person_name:  Yichieh Chen
person_nickname: Jason
description: Software Engineer
description-2: Project Engineer
baseurl: "" # site subpath
url: https://blog.chairco.me # site base hostname & protocol
permalink: /:title/

blog_url: https//chairco.github.io
cv_url: https://registry.jsonresume.org/chairco
twitter_username: ChaircoChen
github_username: chairco
linkedin_username: chairco

# Build settings
markdown: kramdown
